### Recuperando todas las peliculas

GET http://localhost:3000/movies

### Recuperando una pelicula por id

GET http://localhost:3000/movies/93e1926e-86fb-11ef-87f8-58a023aaebc3

### Recuperando las peliculas por genero con query params

GET http://localhost:3000/movies?genre=action

### Crear una pelicula con POST

POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "The goodfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg",
    "genre": ["Crime", "Drama"]
}

### Borrar una pelicula con DELETE
DELETE http://localhost:3000/movies/afe1b85f-8bc1-11ef-94ec-58a023aaebc3

### Actualizar una pelicula con PATCH

PATCH http://localhost:3000/movies/93e19e29-86fb-11ef-87f8-58a023aaebc3
Content-Type: application/json

{
  "year": 1994,
  "duration": 154
}